import '@mantine/core/styles.css'
import '@mantine/notifications/styles.css'
import './globals.css'

import { MantineProvider } from '@mantine/core'
import { Notifications } from '@mantine/notifications'
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
          <body>
            <MantineProvider defaultColorScheme="light">
              <Notifications />
              {children}
            </MantineProvider>
          </body>
    </html>
  );
}
